### ISSUE TITLE
扫码以后 手机端显示二维码扫描过期

### ISSUE THREAD

**Issue by xiaofeng521** [notnotype/zhihuishu-cli#2]

**Comment by notnotype** [comment]
扫快点，一至两分钟内有效

**Comment by xiaofeng521** [comment]
> 扫快点，一至两分钟内有效

我去百度了下。错误。好像是证书没有。python3 不支持https

**Comment by notnotype** [comment]
不是，你自己去智慧树的网站看，它二维码就是会有超时时间的

**Comment by xiaofeng521** [comment]
> 不是，你自己去智慧树的网站看，它二维码就是会有超时时间的
我知道，但是我秒扫也超时

**Comment by xiaofeng521** [comment]
> 不是，你自己去智慧树的网站看，它二维码就是会有超时时间的

()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
输入之后后面有一行这个

**Comment by notnotype** [comment]
图片显示出来了没， 你用什么系统

**Comment by xiaofeng521** [comment]
> 图片显示出来了没， 你用什么系统

用的macos的系统图片显示出来了。 能不能整个输入账号密码的

**Comment by notnotype** [comment]
这是它报错了，没有获取最新的二维码
如果用账号密码的话它会要求你输入图像验证码

**Comment by xiaofeng521** [comment]
> 这是它报错了，没有获取最新的二维码
> 如果用账号密码的话它会要求你输入图像验证码

怎样才能获取最新的验证码

**Comment by notnotype** [comment]
发一下错误信息

**Comment by xiaofeng521** [comment]
> 发一下错误信息

2021-06-02 14:27:41.174 | INFO     | zhihuishu:login:188 - qr_token 为 [9b5a9b5739204a6293e8011de0129485]

Traceback (most recent call last):
  File "路径/zhihuishu-cli.py", line 259, in <module>
    root()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "路径/zhihuishu-cli.py", line 73, in course
    zhs = awesome_login()
  File "路径/zhihuishu-cli.py", line 56, in awesome_login
    zhs.login()
  File "路径/zhihuishu.py", line 194, in login
    password, uuid = self.wait_scan(qr_token)
  File "/zhihuishu.py", line 152, in wait_scan
    ws = create_connection(ws_url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/websocket/_core.py", line 592, in create_connection
    websock.connect(url, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/websocket/_core.py", line 248, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/websocket/_http.py", line 263, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/websocket/_http.py", line 238, in _wrap_sni_socket
    return context.wrap_socket(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

**Comment by notnotype** [comment]
c36145259b0f29bd1146c81e5a2f1d7d160a27e2
禁用ssl认证

**Comment by xiaofeng521** [comment]
> 禁用ssl认证

好的我去百度看看

**Comment by notnotype** [comment]
我更新了
git fetch && git reset FETCH_HEAD --hard

**Comment by xiaofeng521** [comment]
> 我更新了
> git fetch && git reset FETCH_HEAD --hard

我下载试试

**Comment by xiaofeng521** [comment]
> > 我更新了
> > git fetch && git reset FETCH_HEAD --hard
> 
> 我下载试试

好的，我解决了附上解决方案
mac上根治SSL的各种报错python3
> cd "/Applications/Python 3.6/"
> sudo "./Install Certificates.command"

**Comment by xiaofeng521** [comment]
> 我更新了
> git fetch && git reset FETCH_HEAD --hard

你这个只能一个一个的刷吗，能不能一下一门课

**Comment by notnotype** [comment]
run-course 命令

**Comment by xiaofeng521** [comment]
> run-course 命令

 No such file or directory: './mirai/mirai.config.json'
用了命令之后
就出来这个

**Comment by notnotype** [comment]
cp mirai.config.template.json mirai.config.json
